{{cookiecutter.repo_name}}/runtests.py
Django 1.7 throws a warning:
```
?: (1_7.W001) MIDDLEWARE_CLASSES is not set.
HINT: Django 1.7 changed the global defaults for the MIDDLEWARE_CLASSES. django.contrib.sessions.middleware.SessionMiddleware, django.contrib.auth.middleware.AuthenticationMiddleware, and django.contrib.messages.middleware.MessageMiddleware were removed from the defaults. If your project needs these middleware then you should configure this setting.
```
Setting it empty on runtests.py by default might be helpful :)
=> Add MIDDLEWARE_CLASSES to runtests.py

{{cookiecutter.repo_name}}/Makefile
I noticed when I used this project that the help didn't match the actual targets, it was just a matter of adding a dash. Hooray! :smile:
=> Correct help for Makefile to match the test-all target

{{cookiecutter.repo_name}}/Makefile, {{cookiecutter.repo_name}}/README.rst, {{cookiecutter.repo_name}}/docs/usage.rst
The "make docs" command gives an error when your app_name is not the same as the repo_name.
Also fixes the usage.rst to contain the correct default import (the app_name instead of the repo_name)
This should fix it.
=> Fix documentation generation

hooks/pre_gen_project.py
Add a **pre_gen_project** hook to validate ``app_name`` to address the warning in [how-to-create-installable-django-packages](http://www.pydanny.com/how-to-create-installable-django-packages.html) :grin: 
See [cookiecutter docs](https://cookiecutter.readthedocs.org/en/latest/advanced_usage.html#example-validating-template-variables)
=> Validate app name in hook

{{cookiecutter.repo_name}}/setup.py
The `cookiecutter` would be printing out the documentations to use the repo_name, the pypi should also be registered in the same name.
In README.rst
>        pip install {{ cookiecutter.repo_name }}
=> Updated setup.py

{{cookiecutter.repo_name}}/README.rst
The package name is `cookiecutter-djangopackage` instead of `cookiecutter-pypackage`.
=> Updated README.rst

{{cookiecutter.repo_name}}/setup.py
The variable in setup.py is supposed to be named *file_paths but it is named *parts instead. This patch fixes that.
=> Fixes variable name in setup.py

{{cookiecutter.repo_name}}/CONTRIBUTING.rst
Two steps in the numbered list had text, a code block and more text. That text was rendered at the body level rather than as part of the list. This commit adjusts the indentation so the code blocks are indented and the trailing text continues at the level of the the list item text.
=> CONTRIBUTING: fix indents following code blocks

cookiecutter.json
I ran into an error with the default year detection:
```
Unable to render variable 'year'
Error message: 'dict object' has no attribute 'now'
```
I'm not exactly sure where cookiecutter.now is injected, so I went ahead and extracted the year from the local time (same method as how the default date is calculated.)
=> extract year from local time

cookiecutter.json, hooks/pre_gen_project.py, {{cookiecutter.repo_name}}/setup.py, {{cookiecutter.repo_name}}/tox.ini
related to #49 
There are remaining references to Django & Python versions in CONTRIBUTING.md that I am not quite adept enough with the templating system to customize. I am also not sure whether this should change the Travis CI configuration, or requirements.txt & requirements-test.txt.
=> Allow ability to specify Django versions to run tests against in tox

tests/test_bake_project.py, {{cookiecutter.repo_name}}/{{cookiecutter.app_name}}/models.py, {{cookiecutter.repo_name}}/{{cookiecutter.app_name}}/views.py
On this pr we have:
* test for views with models being defined
* test for views without models being defined
* test for url with models being defined
* test for url without models being defined
* insertion of .strip() to avoid unwanted spaces in the models names
=> tests for urls and views and correting model.strip() in some places

.github/ISSUE_TEMPLATE.md, {{cookiecutter.repo_name}}/.github/ISSUE_TEMPLATE.md
Create a GitHub issue template for cookiecutter-djangopackage and also for the generated project.
=> Add issue templates to cookiecutter-djangopackage and generated project

tests/test_bake_project.py
Looks like some code has not been pushed, in the mean time update
the test to match code.
=> tests: there's not such thing as get_version

README.rst, cookiecutter.json, hooks/pre_gen_project.py, {{cookiecutter.repo_name}}/setup.py, {{cookiecutter.repo_name}}/tox.ini
Add support for 1.10 by default and drop support for 1.7 as it's unsupported upstream.
=> Update django versions

tests/test_bake_project.py, {{cookiecutter.repo_name}}/.travis.yml, {{cookiecutter.repo_name}}/README.rst, {{cookiecutter.repo_name}}/requirements.txt, {{cookiecutter.repo_name}}/requirements_dev.txt, {{cookiecutter.repo_name}}/requirements_test.txt, {{cookiecutter.repo_name}}/tox.ini
Relates to #107. Remove Django from `requirements*.txt`, and let Tox manage installation of the right version. Not sure if should be removed from the main `requirements.txt` though?
Feeding back after tweaking the result of cookie cutter for: https://github.com/browniebroke/django-acme
=> Setup to use Tox and fix Tox envlist 

{{cookiecutter.repo_name}}/setup.cfg
- Set max-line-length same as [from Django](https://github.com/django/django/blob/master/setup.cfg) itself.
- Disable D203 disabled as it [conflicts](https://gitlab.com/pycqa/flake8-docstrings/issues/8) with other recommendations.
- Exclude a few files we don't want processed by flake8
=> Set a sensible config for flake8 in setup.cfg

{{cookiecutter.repo_name}}/setup.cfg
- Missing comma at the end of line with ’.tox’
- Correct path of docs’ conf.py
- Exclude migrations folder
=> Fix flake8 config in setup.cfg

{{cookiecutter.repo_name}}/Makefile
I went down this rabbit-hole: https://nedbatchelder.com/blog/201804/makefile_help_target.html, figured I could simplify the upstream source that we got it from.
=> Remove the need for Perl

README.rst
When running `cookiecutter gh:pydanny/cookiecutter-djangopackage.git` it returned an error saying `The repository https://github.com/pydanny/cookiecutter-djangopackage.git.git could not be found, have you made a typo?`.
=> Small typo in the README file.

{{cookiecutter.repo_name}}/{{cookiecutter.app_name}}/admin.py
When I create a new django app, I almost invariably want an admin interface for my models. Since I'm not using the cookiecutter for all new Django projects, figured I'd offer a barebones template to start from.
=> Build admin.py boilerplate

{{cookiecutter.repo_name}}/setup.py
There is also a mix-up between cookiecutter.models which is used in for the requirements.txt, rather there should be an option to specify required packages when creating the package.
=> Pull requirements from requirements.txt
